package _converter_;


import java.util.Locale;
import java.util.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SudiptaaRumu
 */
public class HeightFrame extends javax.swing.JFrame {
    
    double ft_inch=12;
    double cm_inch=0.3937;
    double ft_cm=30.48;
   
                                                                                                                                                                                                                                                                                                          


    public HeightFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jComboTo = new javax.swing.JComboBox<>();
        jLabelConvert = new javax.swing.JLabel();
        jTextCurrency = new javax.swing.JTextField();
        jButtonConvert = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jComboFrom = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("Height Converter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 30, 390, 58);

        jComboTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Unit", "Foot", "Inch", "Centimeter" }));
        jComboTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboToActionPerformed(evt);
            }
        });
        getContentPane().add(jComboTo);
        jComboTo.setBounds(320, 125, 185, 40);

        jLabelConvert.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        jLabelConvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 7));
        getContentPane().add(jLabelConvert);
        jLabelConvert.setBounds(176, 342, 185, 50);

        jTextCurrency.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCurrencyActionPerformed(evt);
            }
        });
        getContentPane().add(jTextCurrency);
        jTextCurrency.setBounds(176, 209, 185, 43);

        jButtonConvert.setBackground(new java.awt.Color(255, 102, 51));
        jButtonConvert.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButtonConvert.setText("Convert");
        jButtonConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConvert);
        jButtonConvert.setBounds(195, 281, 140, 50);

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReset);
        jButtonReset.setBounds(230, 430, 100, 40);

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit);
        jButtonExit.setBounds(415, 427, 90, 40);

        jComboFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Unit", "Foot", "Inch", "Centimeter", " " }));
        jComboFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboFromActionPerformed(evt);
            }
        });
        getContentPane().add(jComboFrom);
        jComboFrom.setBounds(56, 125, 171, 40);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("TO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(255, 133, 22, 21);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 430, 90, 40);

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_converter_/height.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 560, 510);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 30, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboToActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextCurrency.setText(null);
        jComboTo.setSelectedIndex(0);
        jComboFrom.setSelectedIndex(0);
        jLabelConvert.setText(null);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertActionPerformed
        // TODO add your handling code here:
        
     try{ 
         
      
              double value= Double.parseDouble(jTextCurrency.getText());
        
        if(jComboFrom.getSelectedItem().equals("Foot") && jComboTo.getSelectedItem().equals("Inch") )
                {
                    String res= String.format("Inch %.2f",value * ft_inch);
                    jLabelConvert.setText(res);
                }
         if(jComboFrom.getSelectedItem().equals("Inch") && jComboTo.getSelectedItem().equals("Foot") )
                {
                    String res= String.format("Foot %.2f",value / ft_inch);
                    jLabelConvert.setText(res);
                }
          if(jComboFrom.getSelectedItem().equals("Foot") && jComboTo.getSelectedItem().equals("Centimeter") )
                {
                    String res= String.format("cm %.2f",value * ft_cm);
                    jLabelConvert.setText(res);
                }
          
           if(jComboFrom.getSelectedItem().equals("Centimeter") && jComboTo.getSelectedItem().equals("Foot") )
                {
                    String res= String.format("foot %.2f",value / ft_cm);
                    jLabelConvert.setText(res);
                }
            if(jComboFrom.getSelectedItem().equals("Centimeter") && jComboTo.getSelectedItem().equals("Inch") )
                {
                    String res= String.format("inch %.2f",value / cm_inch);
                    jLabelConvert.setText(res);
                }
             if(jComboFrom.getSelectedItem().equals("Inch") && jComboTo.getSelectedItem().equals("Centimeter") )
                {
                    String res= String.format("cm %.2f",value / cm_inch);
                    jLabelConvert.setText(res);
                }
        
      }catch(NumberFormatException e)
       
       {
          JOptionPane.showMessageDialog(null, "InValid Format!!");
       }
   
     
    }//GEN-LAST:event_jButtonConvertActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jTextCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCurrencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCurrencyActionPerformed

    private void jComboFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboFromActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new HomeFrame().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConvert;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox<String> jComboFrom;
    private javax.swing.JComboBox<String> jComboTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelConvert;
    private javax.swing.JTextField jTextCurrency;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
